### PR TITLE
fix: add premade snapshot to speed up test runner

### PR DESCRIPTION
**Pull request by vaeng**
To complete  `run-tests-in-docker.sh` my system needs about 52 seconds. If I edit the `run.sh` file and remove `dart pub upgrade --offline > "${build_log_file}"`  that drops to 19 seconds.
Considering the docker container (`--no-cache`) takes about 11 secs to be built, that is a significant reduction.
During the build step there is `RUN dart pub get` so, the dependencies can be cached beforehand.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@vaeng For me, this causes the `run-tests-in-docker.sh` command to hang indefinitely. I think the problem is that you might not have run it on a clean repo, where the previous run would have left artifacts that were used in a subsequent run. Could you try by running `git clean -xdf` first?

**Comment by iHiD** [comment]
> I think the problem is that you might not have run it on a clean repo, where the previous run would have left artifacts that were used in a subsequent run. Could you try by running git clean -xdf first?

Is this a bug or a feature though? Like, could we preload those artefacts into the runner, or are they solution-specific?

**Comment by ErikSchierboom** [comment]
No idea 🤷

**Comment by vaeng** [comment]
Seems like I have to prebuild the snapshot in the container. I can't use my local version. Strange, that should be independent as they are both run in the same docker container configuration...

**Comment by vaeng** [comment]
Looks good now. That was a lot more work than I anticipated, but I hope people can now enjoy the dart track :)

**Comment by vaeng** [comment]
Maybe the copy can be switched to a symbolic link, to make the process faster

**Comment by iHiD** [comment]
If this works (not to doubt it will, but until I see something working in production, I've learnt to be skeptical of all improvements 😂), then I think this could be a serious improvement across many languages. It's something I've wanted to do for a long time (sort of half-compiled stuff) but it's very tricky to get right from what I've seen.

**Comment by ErikSchierboom** [comment]
> It's something I've wanted to do for a long time (sort of half-compiled stuff) but it's very tricky to get right from what I've seen.

There are actually a bunch of tracks that do this already!

**Comment by ErikSchierboom** [comment]
@vaeng This totally works! I have a couple of questions:

1. Could you try the symlink approach? 
2. Is there a way to build the premade part from within the Dockerfile? That would be the best approach, as we then don't need a 19MB binary in this repo.

**Comment by vaeng** [comment]
@ErikSchierboom 
Symlinks are in place, version agnostic.
Binary creation during container build step as well.

**Review by ErikSchierboom — APPROVED** [review]
Lovely! I've added a couple of minor tweaks: https://github.com/exercism/dart-test-runner/pull/75/commits

Thanks a ton for this!

**Comment by ErikSchierboom** [comment]
https://github.com/exercism/dart/pull/519/files opened and merged. Let's test this!

**Comment by ErikSchierboom** [comment]
image

image

**Comment by iHiD** [comment]
Nice work! Don't forget to update the average run time in the config file :)

**Comment by ErikSchierboom** [comment]
I had to as the old value was outside the allowed range 😁

**Pull request merged**
