### PR TITLE
Upgrade to Dart 3.4

### PR DESCRIPTION
**Pull request by fapdash**

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Review by Stargator — CHANGES_REQUESTED** [review]
Per the conversation here: https://github.com/exercism/dart/pull/581

We don't see too much value being added. Current students are potentially using 3.2 and upgrading the test runner without upgrading the exercises, risks breaking student tests.

**Comment by ErikSchierboom** [comment]
@Stargator are there backwards incompatible changes introduced?

**Comment by Stargator** [comment]
Usually, yes. But I'll check the change log for Dart.

**Comment by fapdash** [comment]
Closing as per https://github.com/exercism/dart/pull/581.

**Pull request closed without merging**
