### PR TITLE
Speedup test runner

### LINKED ISSUE #31: Unexplained errors
Apart from hello world, every problem I have attempted so far results in an error that doesn't provide guidance on where to look. For example, here is my code for two fer:

```
String twoFer([String? name = 'you']) {
  return "One for ${name}, one for me.";
}
```

Apart from any glaring flaws I might have in my code (or do I have any?), the test tab shows:

```
An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.
```

Is there something I'm doing wrong? On my CLI, my tests pass, but it seems like my submission is incorrect when I test it on the site.

### PR DESCRIPTION
**Pull request by ErikSchierboom**
In an effort to try to fix #31 and #29, I've done some additional performance testing on my machine (using WSL). Here are my test results.

## Run without Docker

The first test I wanted to do is to check how much overhead Docker has, so I ran the test runner without Docker first using `./bin/run.sh`:

```
real    0m11.665s
user    0m14.408s
sys     0m2.418s
```

## Run with Docker (no networking)

The second test was to run `./bin/run-in-docker.sh` without any modifications, so that means no networking:

```
real    0m24.187s
user    0m0.335s
sys     0m0.282s
```

## Run with Docker (networking)

Just as a sanity check, I ran in Docker without the `--network none`  argument. This did not have any noticeable effect:

```
real    0m24.065s
user    0m0.444s
sys     0m0.147s
```

## Run with Docker (latest image)

I then updated the Docker image to `google/dart:2.14.1` to use the latest stable version:

```
real    0m16.649s
user    0m0.389s
sys     0m0.205s
```

This shaved off 8 seconds on my machine!

## Run with Docker (latest image and updated package)

I then noticed that the packages that are pre-installed were outdated. Most noticeably, the `test` package was on version `1.16.8` and [this issue](https://github.com/dart-lang/test/issues/1567#issuecomment-907290381) seemed to suggest that version `1.17.x` would provide a performance boost.

```
real    0m15.061s
user    0m0.434s
sys     0m0.179s
```

And another 1,5 seconds shaved off!

Side note: these dependencies were updated:

```
> test 1.17.12 (was 1.16.8)
> test_api 0.4.3 (was 0.3.0)
> test_core 0.4.2 (was 0.3.19)
> io 1.0.3 (was 1.0.0)
> matcher 0.12.11 (was 0.12.10)
```

### CODE REVIEW

**Review by iHiD — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@Stargator We'll try out the test runner on our infrastructure to see if this actuall helped.

**Comment by Stargator** [comment]
@ErikSchierboom Thanks for the research. There's also the [dart_test.yaml configuration parameter `concurrency`](https://github.com/dart-lang/test/blob/master/pkgs/test/doc/configuration.md#concurrency) that could improve the speed of the tests.

**Comment by ErikSchierboom** [comment]
@Stargator Would the concurrency parameter help with running test for your typical practice exercise (like https://github.com/exercism/dart/blob/main/exercises/practice/armstrong-numbers/test/armstrong_numbers_test.dart)? Isn't that just one test suite?

**Comment by Stargator** [comment]
@ErikSchierboom 

> @Stargator Would the concurrency parameter help with running test for your typical practice exercise (like https://github.com/exercism/dart/blob/main/exercises/practice/armstrong-numbers/test/armstrong_numbers_test.dart)? Isn't that just one test suite?

@ErikSchierboom Ugh, good catch. I keep forgetting that's just for test suites and not tests.

**Pull request merged**
